<a href="https://colab.research.google.com/github/yeneua/2022-1/blob/main/8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
v1 = numpy.array([1,2,3,4])

NameError: ignored

In [3]:
import numpy as np #패키지 불러오기가 필요 !!

In [4]:
v1 = np.array([1,2,3,4]) #1차원 구조의 리스트
print(v1)

[1 2 3 4]


In [5]:
v1 = np.arange(5) #4(5-1)까지의 연속된 배열. 인덱스를 만들 때 자주 사용
print(v1)

[0 1 2 3 4]


In [7]:
v2 = np.arange(1,10,2) #1~10까지 2 간격
print(v2)

[1 3 5 7 9]


In [8]:
v2 = np.arange(1,10,2)**3
print(v2)

[  1  27 125 343 729]


In [9]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
v2 = v1.reshape(2,6) #구조바꾸기 -> reshape()
v2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
v2 = v1.reshape(2,6, order='F') #자료의 순서
v2

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [16]:
v1 = np.arange(1,5)
v2 = v1.reshape(2,2)
v2

array([[1, 2],
       [3, 4]])

In [18]:
v1 = np.arange(1,5).reshape(2,2) #리스트가 만들어짐과 동시에 reshape
v1

array([[1, 2],
       [3, 4]])

In [19]:
print(np.add(v2,v2)) #더하기 : add

[[2 4]
 [6 8]]


In [20]:
print(np.subtract(v2,v2)) #빼기 : subtract

[[0 0]
 [0 0]]


In [21]:
print(np.multiply(v2,v2)) #곱하기 : multiply

[[ 1  4]
 [ 9 16]]


In [22]:
print(np.dot(v2,v2)) #행렬연산 : dot

[[ 7 10]
 [15 22]]


다차원배열

In [24]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
v2=v1.reshape(2,3,2) #2행 3열 2차원
v2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [28]:
v2 = v1.reshape(2,3,2, order='F') #열단위로 숫자 할당
v2

array([[[ 0,  6],
        [ 2,  8],
        [ 4, 10]],

       [[ 1,  7],
        [ 3,  9],
        [ 5, 11]]])

In [30]:
v3 = np.arange(3.5, 10.5, 2, dtype = float) #데이터 타입 지정해주는 것
print(v3)

[3.5 5.5 7.5 9.5]


In [31]:
v4 = v3.reshape(2,2)
v4

array([[3.5, 5.5],
       [7.5, 9.5]])

In [32]:
print(np.amax(v4)) #최대값

9.5


In [34]:
print(np.amin(v4)) #최소값

3.5


In [35]:
print(v4.dtype) #데이터타입

float64


In [36]:
print(v4.shape) #구조확인

(2, 2)


In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
np.abs(a) #절대값

array([0, 1, 2, 3, 4])

In [40]:
np.sqrt(a) #제곱근

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [41]:
np.square(a) #제곱

array([ 0,  1,  4,  9, 16])

In [42]:
np.exp(a) #지수

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [44]:
np.log(a) #로그

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])